version: '3.7'
services:
  gatsby:
    build: .
    environment:
        NODE_ENV: development
    ports:
      - 8080:8080
    volumes:
      - .:/book
    command: /bin/bash -c "npm install && gatsby develop --verbose -p 8080 --host 0.0.0.0"
